#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_da_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertENTIDADRECIBOSUELDO(ENTIDADRECIBOSUELDO instance);
    partial void UpdateENTIDADRECIBOSUELDO(ENTIDADRECIBOSUELDO instance);
    partial void DeleteENTIDADRECIBOSUELDO(ENTIDADRECIBOSUELDO instance);
    partial void InsertENTIDADCONTRATOALQUILER(ENTIDADCONTRATOALQUILER instance);
    partial void UpdateENTIDADCONTRATOALQUILER(ENTIDADCONTRATOALQUILER instance);
    partial void DeleteENTIDADCONTRATOALQUILER(ENTIDADCONTRATOALQUILER instance);
    partial void InsertENTIDADDUENIO(ENTIDADDUENIO instance);
    partial void UpdateENTIDADDUENIO(ENTIDADDUENIO instance);
    partial void DeleteENTIDADDUENIO(ENTIDADDUENIO instance);
    partial void InsertENTIDADGARANTE(ENTIDADGARANTE instance);
    partial void UpdateENTIDADGARANTE(ENTIDADGARANTE instance);
    partial void DeleteENTIDADGARANTE(ENTIDADGARANTE instance);
    partial void InsertENTIDADINQUILINO(ENTIDADINQUILINO instance);
    partial void UpdateENTIDADINQUILINO(ENTIDADINQUILINO instance);
    partial void DeleteENTIDADINQUILINO(ENTIDADINQUILINO instance);
    partial void InsertENTIDADOTROS(ENTIDADOTROS instance);
    partial void UpdateENTIDADOTROS(ENTIDADOTROS instance);
    partial void DeleteENTIDADOTROS(ENTIDADOTROS instance);
    partial void InsertENTIDADLOCALCOMERCIAL(ENTIDADLOCALCOMERCIAL instance);
    partial void UpdateENTIDADLOCALCOMERCIAL(ENTIDADLOCALCOMERCIAL instance);
    partial void DeleteENTIDADLOCALCOMERCIAL(ENTIDADLOCALCOMERCIAL instance);
    partial void InsertENTIDADDEPARTAMENTO(ENTIDADDEPARTAMENTO instance);
    partial void UpdateENTIDADDEPARTAMENTO(ENTIDADDEPARTAMENTO instance);
    partial void DeleteENTIDADDEPARTAMENTO(ENTIDADDEPARTAMENTO instance);
    partial void InsertENTIDADCASA(ENTIDADCASA instance);
    partial void UpdateENTIDADCASA(ENTIDADCASA instance);
    partial void DeleteENTIDADCASA(ENTIDADCASA instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Capa_da_Datos.Properties.Settings.Default.Database1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ENTIDADRECIBOSUELDO> ENTIDADRECIBOSUELDO
		{
			get
			{
				return this.GetTable<ENTIDADRECIBOSUELDO>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADCONTRATOALQUILER> ENTIDADCONTRATOALQUILER
		{
			get
			{
				return this.GetTable<ENTIDADCONTRATOALQUILER>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADDUENIO> ENTIDADDUENIO
		{
			get
			{
				return this.GetTable<ENTIDADDUENIO>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADGARANTE> ENTIDADGARANTE
		{
			get
			{
				return this.GetTable<ENTIDADGARANTE>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADINQUILINO> ENTIDADINQUILINO
		{
			get
			{
				return this.GetTable<ENTIDADINQUILINO>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADOTROS> ENTIDADOTROS
		{
			get
			{
				return this.GetTable<ENTIDADOTROS>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADLOCALCOMERCIAL> ENTIDADLOCALCOMERCIAL
		{
			get
			{
				return this.GetTable<ENTIDADLOCALCOMERCIAL>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADDEPARTAMENTO> ENTIDADDEPARTAMENTO
		{
			get
			{
				return this.GetTable<ENTIDADDEPARTAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<ENTIDADCASA> ENTIDADCASA
		{
			get
			{
				return this.GetTable<ENTIDADCASA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReciboSuelo")]
	public partial class ENTIDADRECIBOSUELDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdReciboSueldo;
		
		private string _Detalle;
		
		private string _Sueldo;
		
		private string _IdGarante;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdReciboSueldoChanging(int value);
    partial void OnIdReciboSueldoChanged();
    partial void OnDetalleChanging(string value);
    partial void OnDetalleChanged();
    partial void OnSueldoChanging(string value);
    partial void OnSueldoChanged();
    partial void OnIdGaranteChanging(string value);
    partial void OnIdGaranteChanged();
    #endregion
		
		public ENTIDADRECIBOSUELDO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReciboSueldo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdReciboSueldo
		{
			get
			{
				return this._IdReciboSueldo;
			}
			set
			{
				if ((this._IdReciboSueldo != value))
				{
					this.OnIdReciboSueldoChanging(value);
					this.SendPropertyChanging();
					this._IdReciboSueldo = value;
					this.SendPropertyChanged("IdReciboSueldo");
					this.OnIdReciboSueldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="VarChar(50)")]
		public string Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this.OnDetalleChanging(value);
					this.SendPropertyChanging();
					this._Detalle = value;
					this.SendPropertyChanged("Detalle");
					this.OnDetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sueldo", DbType="VarChar(50)")]
		public string Sueldo
		{
			get
			{
				return this._Sueldo;
			}
			set
			{
				if ((this._Sueldo != value))
				{
					this.OnSueldoChanging(value);
					this.SendPropertyChanging();
					this._Sueldo = value;
					this.SendPropertyChanged("Sueldo");
					this.OnSueldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGarante", DbType="VarChar(50)")]
		public string IdGarante
		{
			get
			{
				return this._IdGarante;
			}
			set
			{
				if ((this._IdGarante != value))
				{
					this.OnIdGaranteChanging(value);
					this.SendPropertyChanging();
					this._IdGarante = value;
					this.SendPropertyChanged("IdGarante");
					this.OnIdGaranteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContratoAlquiler")]
	public partial class ENTIDADCONTRATOALQUILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdContratoAlquiler;
		
		private System.Nullable<int> _IdGarante;
		
		private System.Nullable<int> _IdDuenio;
		
		private System.Nullable<int> _IdInquilino;
		
		private System.Nullable<int> _IdInmueble;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<int> _Meses;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdContratoAlquilerChanging(int value);
    partial void OnIdContratoAlquilerChanged();
    partial void OnIdGaranteChanging(System.Nullable<int> value);
    partial void OnIdGaranteChanged();
    partial void OnIdDuenioChanging(System.Nullable<int> value);
    partial void OnIdDuenioChanged();
    partial void OnIdInquilinoChanging(System.Nullable<int> value);
    partial void OnIdInquilinoChanged();
    partial void OnIdInmuebleChanging(System.Nullable<int> value);
    partial void OnIdInmuebleChanged();
    partial void OnFechaInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaInicioChanged();
    partial void OnMesesChanging(System.Nullable<int> value);
    partial void OnMesesChanged();
    #endregion
		
		public ENTIDADCONTRATOALQUILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContratoAlquiler", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdContratoAlquiler
		{
			get
			{
				return this._IdContratoAlquiler;
			}
			set
			{
				if ((this._IdContratoAlquiler != value))
				{
					this.OnIdContratoAlquilerChanging(value);
					this.SendPropertyChanging();
					this._IdContratoAlquiler = value;
					this.SendPropertyChanged("IdContratoAlquiler");
					this.OnIdContratoAlquilerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGarante", DbType="Int")]
		public System.Nullable<int> IdGarante
		{
			get
			{
				return this._IdGarante;
			}
			set
			{
				if ((this._IdGarante != value))
				{
					this.OnIdGaranteChanging(value);
					this.SendPropertyChanging();
					this._IdGarante = value;
					this.SendPropertyChanged("IdGarante");
					this.OnIdGaranteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDuenio", DbType="Int")]
		public System.Nullable<int> IdDuenio
		{
			get
			{
				return this._IdDuenio;
			}
			set
			{
				if ((this._IdDuenio != value))
				{
					this.OnIdDuenioChanging(value);
					this.SendPropertyChanging();
					this._IdDuenio = value;
					this.SendPropertyChanged("IdDuenio");
					this.OnIdDuenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInquilino", DbType="Int")]
		public System.Nullable<int> IdInquilino
		{
			get
			{
				return this._IdInquilino;
			}
			set
			{
				if ((this._IdInquilino != value))
				{
					this.OnIdInquilinoChanging(value);
					this.SendPropertyChanging();
					this._IdInquilino = value;
					this.SendPropertyChanged("IdInquilino");
					this.OnIdInquilinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInmueble", DbType="Int")]
		public System.Nullable<int> IdInmueble
		{
			get
			{
				return this._IdInmueble;
			}
			set
			{
				if ((this._IdInmueble != value))
				{
					this.OnIdInmuebleChanging(value);
					this.SendPropertyChanging();
					this._IdInmueble = value;
					this.SendPropertyChanged("IdInmueble");
					this.OnIdInmuebleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meses", DbType="Int")]
		public System.Nullable<int> Meses
		{
			get
			{
				return this._Meses;
			}
			set
			{
				if ((this._Meses != value))
				{
					this.OnMesesChanging(value);
					this.SendPropertyChanging();
					this._Meses = value;
					this.SendPropertyChanged("Meses");
					this.OnMesesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Duenio")]
	public partial class ENTIDADDUENIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDuenio;
		
		private string _Apellido;
		
		private string _Nombre;
		
		private string _DNI;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Mail;
		
		private string _Banco;
		
		private string _NumeroCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDuenioChanging(int value);
    partial void OnIdDuenioChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnBancoChanging(string value);
    partial void OnBancoChanged();
    partial void OnNumeroCuentaChanging(string value);
    partial void OnNumeroCuentaChanged();
    #endregion
		
		public ENTIDADDUENIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDuenio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdDuenio
		{
			get
			{
				return this._IdDuenio;
			}
			set
			{
				if ((this._IdDuenio != value))
				{
					this.OnIdDuenioChanging(value);
					this.SendPropertyChanging();
					this._IdDuenio = value;
					this.SendPropertyChanged("IdDuenio");
					this.OnIdDuenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(50)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banco", DbType="VarChar(50)")]
		public string Banco
		{
			get
			{
				return this._Banco;
			}
			set
			{
				if ((this._Banco != value))
				{
					this.OnBancoChanging(value);
					this.SendPropertyChanging();
					this._Banco = value;
					this.SendPropertyChanged("Banco");
					this.OnBancoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCuenta", DbType="VarChar(50)")]
		public string NumeroCuenta
		{
			get
			{
				return this._NumeroCuenta;
			}
			set
			{
				if ((this._NumeroCuenta != value))
				{
					this.OnNumeroCuentaChanging(value);
					this.SendPropertyChanging();
					this._NumeroCuenta = value;
					this.SendPropertyChanged("NumeroCuenta");
					this.OnNumeroCuentaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Garante")]
	public partial class ENTIDADGARANTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGarante;
		
		private string _Apellido;
		
		private string _Nombre;
		
		private string _DNI;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Mail;
		
		private string _Empleo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGaranteChanging(int value);
    partial void OnIdGaranteChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnEmpleoChanging(string value);
    partial void OnEmpleoChanged();
    #endregion
		
		public ENTIDADGARANTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGarante", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdGarante
		{
			get
			{
				return this._IdGarante;
			}
			set
			{
				if ((this._IdGarante != value))
				{
					this.OnIdGaranteChanging(value);
					this.SendPropertyChanging();
					this._IdGarante = value;
					this.SendPropertyChanged("IdGarante");
					this.OnIdGaranteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(50)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleo", DbType="VarChar(50)")]
		public string Empleo
		{
			get
			{
				return this._Empleo;
			}
			set
			{
				if ((this._Empleo != value))
				{
					this.OnEmpleoChanging(value);
					this.SendPropertyChanging();
					this._Empleo = value;
					this.SendPropertyChanged("Empleo");
					this.OnEmpleoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inquilino")]
	public partial class ENTIDADINQUILINO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdInquilino;
		
		private string _Apellido;
		
		private string _Nombre;
		
		private string _DNI;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Mail;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdInquilinoChanging(int value);
    partial void OnIdInquilinoChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    #endregion
		
		public ENTIDADINQUILINO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInquilino", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdInquilino
		{
			get
			{
				return this._IdInquilino;
			}
			set
			{
				if ((this._IdInquilino != value))
				{
					this.OnIdInquilinoChanging(value);
					this.SendPropertyChanging();
					this._IdInquilino = value;
					this.SendPropertyChanged("IdInquilino");
					this.OnIdInquilinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(50)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Otros")]
	public partial class ENTIDADOTROS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdOtros;
		
		private System.Nullable<int> _Ascensor;
		
		private System.Nullable<int> _Cochera;
		
		private System.Nullable<int> _Piscina;
		
		private System.Nullable<int> _Portero;
		
		private System.Nullable<int> _IdDepartamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdOtrosChanging(int value);
    partial void OnIdOtrosChanged();
    partial void OnAscensorChanging(System.Nullable<int> value);
    partial void OnAscensorChanged();
    partial void OnCocheraChanging(System.Nullable<int> value);
    partial void OnCocheraChanged();
    partial void OnPiscinaChanging(System.Nullable<int> value);
    partial void OnPiscinaChanged();
    partial void OnPorteroChanging(System.Nullable<int> value);
    partial void OnPorteroChanged();
    partial void OnIdDepartamentoChanging(System.Nullable<int> value);
    partial void OnIdDepartamentoChanged();
    #endregion
		
		public ENTIDADOTROS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOtros", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdOtros
		{
			get
			{
				return this._IdOtros;
			}
			set
			{
				if ((this._IdOtros != value))
				{
					this.OnIdOtrosChanging(value);
					this.SendPropertyChanging();
					this._IdOtros = value;
					this.SendPropertyChanged("IdOtros");
					this.OnIdOtrosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ascensor", DbType="Int")]
		public System.Nullable<int> Ascensor
		{
			get
			{
				return this._Ascensor;
			}
			set
			{
				if ((this._Ascensor != value))
				{
					this.OnAscensorChanging(value);
					this.SendPropertyChanging();
					this._Ascensor = value;
					this.SendPropertyChanged("Ascensor");
					this.OnAscensorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cochera", DbType="Int")]
		public System.Nullable<int> Cochera
		{
			get
			{
				return this._Cochera;
			}
			set
			{
				if ((this._Cochera != value))
				{
					this.OnCocheraChanging(value);
					this.SendPropertyChanging();
					this._Cochera = value;
					this.SendPropertyChanged("Cochera");
					this.OnCocheraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piscina", DbType="Int")]
		public System.Nullable<int> Piscina
		{
			get
			{
				return this._Piscina;
			}
			set
			{
				if ((this._Piscina != value))
				{
					this.OnPiscinaChanging(value);
					this.SendPropertyChanging();
					this._Piscina = value;
					this.SendPropertyChanged("Piscina");
					this.OnPiscinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portero", DbType="Int")]
		public System.Nullable<int> Portero
		{
			get
			{
				return this._Portero;
			}
			set
			{
				if ((this._Portero != value))
				{
					this.OnPorteroChanging(value);
					this.SendPropertyChanging();
					this._Portero = value;
					this.SendPropertyChanged("Portero");
					this.OnPorteroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartamento", DbType="Int")]
		public System.Nullable<int> IdDepartamento
		{
			get
			{
				return this._IdDepartamento;
			}
			set
			{
				if ((this._IdDepartamento != value))
				{
					this.OnIdDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._IdDepartamento = value;
					this.SendPropertyChanged("IdDepartamento");
					this.OnIdDepartamentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LocalComercial")]
	public partial class ENTIDADLOCALCOMERCIAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLocalComercial;
		
		private string _CantidadAmbientes;
		
		private string _Descripcion;
		
		private string _Direccion;
		
		private string _Tamnio;
		
		private string _Banios;
		
		private string _CantidadOficinas;
		
		private string _Cocina;
		
		private string _TamanioFente;
		
		private System.Data.Linq.Binary _Foto;
		
		private System.Nullable<int> _IdInquilino;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLocalComercialChanging(int value);
    partial void OnIdLocalComercialChanged();
    partial void OnCantidadAmbientesChanging(string value);
    partial void OnCantidadAmbientesChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTamnioChanging(string value);
    partial void OnTamnioChanged();
    partial void OnBaniosChanging(string value);
    partial void OnBaniosChanged();
    partial void OnCantidadOficinasChanging(string value);
    partial void OnCantidadOficinasChanged();
    partial void OnCocinaChanging(string value);
    partial void OnCocinaChanged();
    partial void OnTamanioFenteChanging(string value);
    partial void OnTamanioFenteChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnIdInquilinoChanging(System.Nullable<int> value);
    partial void OnIdInquilinoChanged();
    #endregion
		
		public ENTIDADLOCALCOMERCIAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocalComercial", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdLocalComercial
		{
			get
			{
				return this._IdLocalComercial;
			}
			set
			{
				if ((this._IdLocalComercial != value))
				{
					this.OnIdLocalComercialChanging(value);
					this.SendPropertyChanging();
					this._IdLocalComercial = value;
					this.SendPropertyChanged("IdLocalComercial");
					this.OnIdLocalComercialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadAmbientes", DbType="VarChar(50)")]
		public string CantidadAmbientes
		{
			get
			{
				return this._CantidadAmbientes;
			}
			set
			{
				if ((this._CantidadAmbientes != value))
				{
					this.OnCantidadAmbientesChanging(value);
					this.SendPropertyChanging();
					this._CantidadAmbientes = value;
					this.SendPropertyChanged("CantidadAmbientes");
					this.OnCantidadAmbientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tamnio", DbType="VarChar(50)")]
		public string Tamnio
		{
			get
			{
				return this._Tamnio;
			}
			set
			{
				if ((this._Tamnio != value))
				{
					this.OnTamnioChanging(value);
					this.SendPropertyChanging();
					this._Tamnio = value;
					this.SendPropertyChanged("Tamnio");
					this.OnTamnioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banios", DbType="VarChar(50)")]
		public string Banios
		{
			get
			{
				return this._Banios;
			}
			set
			{
				if ((this._Banios != value))
				{
					this.OnBaniosChanging(value);
					this.SendPropertyChanging();
					this._Banios = value;
					this.SendPropertyChanged("Banios");
					this.OnBaniosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadOficinas", DbType="VarChar(50)")]
		public string CantidadOficinas
		{
			get
			{
				return this._CantidadOficinas;
			}
			set
			{
				if ((this._CantidadOficinas != value))
				{
					this.OnCantidadOficinasChanging(value);
					this.SendPropertyChanging();
					this._CantidadOficinas = value;
					this.SendPropertyChanged("CantidadOficinas");
					this.OnCantidadOficinasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cocina", DbType="VarChar(50)")]
		public string Cocina
		{
			get
			{
				return this._Cocina;
			}
			set
			{
				if ((this._Cocina != value))
				{
					this.OnCocinaChanging(value);
					this.SendPropertyChanging();
					this._Cocina = value;
					this.SendPropertyChanged("Cocina");
					this.OnCocinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamanioFente", DbType="VarChar(50)")]
		public string TamanioFente
		{
			get
			{
				return this._TamanioFente;
			}
			set
			{
				if ((this._TamanioFente != value))
				{
					this.OnTamanioFenteChanging(value);
					this.SendPropertyChanging();
					this._TamanioFente = value;
					this.SendPropertyChanged("TamanioFente");
					this.OnTamanioFenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInquilino", DbType="Int")]
		public System.Nullable<int> IdInquilino
		{
			get
			{
				return this._IdInquilino;
			}
			set
			{
				if ((this._IdInquilino != value))
				{
					this.OnIdInquilinoChanging(value);
					this.SendPropertyChanging();
					this._IdInquilino = value;
					this.SendPropertyChanged("IdInquilino");
					this.OnIdInquilinoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class ENTIDADDEPARTAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDepartamento;
		
		private string _CantidadAmbientes;
		
		private string _Descipcion;
		
		private string _Direccion;
		
		private string _Tamanio;
		
		private string _Balcones;
		
		private string _Expensas;
		
		private string _Piso;
		
		private string _Puerta;
		
		private System.Data.Linq.Binary _Foto;
		
		private System.Nullable<int> _IdInquilino;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDepartamentoChanging(int value);
    partial void OnIdDepartamentoChanged();
    partial void OnCantidadAmbientesChanging(string value);
    partial void OnCantidadAmbientesChanged();
    partial void OnDescipcionChanging(string value);
    partial void OnDescipcionChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTamanioChanging(string value);
    partial void OnTamanioChanged();
    partial void OnBalconesChanging(string value);
    partial void OnBalconesChanged();
    partial void OnExpensasChanging(string value);
    partial void OnExpensasChanged();
    partial void OnPisoChanging(string value);
    partial void OnPisoChanged();
    partial void OnPuertaChanging(string value);
    partial void OnPuertaChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnIdInquilinoChanging(System.Nullable<int> value);
    partial void OnIdInquilinoChanged();
    #endregion
		
		public ENTIDADDEPARTAMENTO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDepartamento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdDepartamento
		{
			get
			{
				return this._IdDepartamento;
			}
			set
			{
				if ((this._IdDepartamento != value))
				{
					this.OnIdDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._IdDepartamento = value;
					this.SendPropertyChanged("IdDepartamento");
					this.OnIdDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadAmbientes", DbType="VarChar(50)")]
		public string CantidadAmbientes
		{
			get
			{
				return this._CantidadAmbientes;
			}
			set
			{
				if ((this._CantidadAmbientes != value))
				{
					this.OnCantidadAmbientesChanging(value);
					this.SendPropertyChanging();
					this._CantidadAmbientes = value;
					this.SendPropertyChanged("CantidadAmbientes");
					this.OnCantidadAmbientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descipcion", DbType="VarChar(50)")]
		public string Descipcion
		{
			get
			{
				return this._Descipcion;
			}
			set
			{
				if ((this._Descipcion != value))
				{
					this.OnDescipcionChanging(value);
					this.SendPropertyChanging();
					this._Descipcion = value;
					this.SendPropertyChanged("Descipcion");
					this.OnDescipcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tamanio", DbType="VarChar(50)")]
		public string Tamanio
		{
			get
			{
				return this._Tamanio;
			}
			set
			{
				if ((this._Tamanio != value))
				{
					this.OnTamanioChanging(value);
					this.SendPropertyChanging();
					this._Tamanio = value;
					this.SendPropertyChanged("Tamanio");
					this.OnTamanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balcones", DbType="VarChar(50)")]
		public string Balcones
		{
			get
			{
				return this._Balcones;
			}
			set
			{
				if ((this._Balcones != value))
				{
					this.OnBalconesChanging(value);
					this.SendPropertyChanging();
					this._Balcones = value;
					this.SendPropertyChanged("Balcones");
					this.OnBalconesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expensas", DbType="VarChar(50)")]
		public string Expensas
		{
			get
			{
				return this._Expensas;
			}
			set
			{
				if ((this._Expensas != value))
				{
					this.OnExpensasChanging(value);
					this.SendPropertyChanging();
					this._Expensas = value;
					this.SendPropertyChanged("Expensas");
					this.OnExpensasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piso", DbType="VarChar(50)")]
		public string Piso
		{
			get
			{
				return this._Piso;
			}
			set
			{
				if ((this._Piso != value))
				{
					this.OnPisoChanging(value);
					this.SendPropertyChanging();
					this._Piso = value;
					this.SendPropertyChanged("Piso");
					this.OnPisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puerta", DbType="VarChar(50)")]
		public string Puerta
		{
			get
			{
				return this._Puerta;
			}
			set
			{
				if ((this._Puerta != value))
				{
					this.OnPuertaChanging(value);
					this.SendPropertyChanging();
					this._Puerta = value;
					this.SendPropertyChanged("Puerta");
					this.OnPuertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInquilino", DbType="Int")]
		public System.Nullable<int> IdInquilino
		{
			get
			{
				return this._IdInquilino;
			}
			set
			{
				if ((this._IdInquilino != value))
				{
					this.OnIdInquilinoChanging(value);
					this.SendPropertyChanging();
					this._IdInquilino = value;
					this.SendPropertyChanged("IdInquilino");
					this.OnIdInquilinoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Casa")]
	public partial class ENTIDADCASA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCasa;
		
		private string _Descipcion;
		
		private string _Direccion;
		
		private string _Tamanio;
		
		private string _Banios;
		
		private string _CantidadPisos;
		
		private string _Habitaciones;
		
		private string _TamanioJardin;
		
		private string _TamanioPatio;
		
		private System.Data.Linq.Binary _Foto;
		
		private string _CantidadAmbientes;
		
		private System.Nullable<int> _IdInquilino;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCasaChanging(int value);
    partial void OnIdCasaChanged();
    partial void OnDescipcionChanging(string value);
    partial void OnDescipcionChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTamanioChanging(string value);
    partial void OnTamanioChanged();
    partial void OnBaniosChanging(string value);
    partial void OnBaniosChanged();
    partial void OnCantidadPisosChanging(string value);
    partial void OnCantidadPisosChanged();
    partial void OnHabitacionesChanging(string value);
    partial void OnHabitacionesChanged();
    partial void OnTamanioJardinChanging(string value);
    partial void OnTamanioJardinChanged();
    partial void OnTamanioPatioChanging(string value);
    partial void OnTamanioPatioChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnCantidadAmbientesChanging(string value);
    partial void OnCantidadAmbientesChanged();
    partial void OnIdInquilinoChanging(System.Nullable<int> value);
    partial void OnIdInquilinoChanged();
    #endregion
		
		public ENTIDADCASA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCasa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCasa
		{
			get
			{
				return this._IdCasa;
			}
			set
			{
				if ((this._IdCasa != value))
				{
					this.OnIdCasaChanging(value);
					this.SendPropertyChanging();
					this._IdCasa = value;
					this.SendPropertyChanged("IdCasa");
					this.OnIdCasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descipcion", DbType="VarChar(50)")]
		public string Descipcion
		{
			get
			{
				return this._Descipcion;
			}
			set
			{
				if ((this._Descipcion != value))
				{
					this.OnDescipcionChanging(value);
					this.SendPropertyChanging();
					this._Descipcion = value;
					this.SendPropertyChanged("Descipcion");
					this.OnDescipcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tamanio", DbType="VarChar(50)")]
		public string Tamanio
		{
			get
			{
				return this._Tamanio;
			}
			set
			{
				if ((this._Tamanio != value))
				{
					this.OnTamanioChanging(value);
					this.SendPropertyChanging();
					this._Tamanio = value;
					this.SendPropertyChanged("Tamanio");
					this.OnTamanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banios", DbType="VarChar(50)")]
		public string Banios
		{
			get
			{
				return this._Banios;
			}
			set
			{
				if ((this._Banios != value))
				{
					this.OnBaniosChanging(value);
					this.SendPropertyChanging();
					this._Banios = value;
					this.SendPropertyChanged("Banios");
					this.OnBaniosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadPisos", DbType="VarChar(50)")]
		public string CantidadPisos
		{
			get
			{
				return this._CantidadPisos;
			}
			set
			{
				if ((this._CantidadPisos != value))
				{
					this.OnCantidadPisosChanging(value);
					this.SendPropertyChanging();
					this._CantidadPisos = value;
					this.SendPropertyChanged("CantidadPisos");
					this.OnCantidadPisosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Habitaciones", DbType="VarChar(50)")]
		public string Habitaciones
		{
			get
			{
				return this._Habitaciones;
			}
			set
			{
				if ((this._Habitaciones != value))
				{
					this.OnHabitacionesChanging(value);
					this.SendPropertyChanging();
					this._Habitaciones = value;
					this.SendPropertyChanged("Habitaciones");
					this.OnHabitacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamanioJardin", DbType="VarChar(50)")]
		public string TamanioJardin
		{
			get
			{
				return this._TamanioJardin;
			}
			set
			{
				if ((this._TamanioJardin != value))
				{
					this.OnTamanioJardinChanging(value);
					this.SendPropertyChanging();
					this._TamanioJardin = value;
					this.SendPropertyChanged("TamanioJardin");
					this.OnTamanioJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TamanioPatio", DbType="VarChar(50)")]
		public string TamanioPatio
		{
			get
			{
				return this._TamanioPatio;
			}
			set
			{
				if ((this._TamanioPatio != value))
				{
					this.OnTamanioPatioChanging(value);
					this.SendPropertyChanging();
					this._TamanioPatio = value;
					this.SendPropertyChanged("TamanioPatio");
					this.OnTamanioPatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadAmbientes", DbType="NChar(10)")]
		public string CantidadAmbientes
		{
			get
			{
				return this._CantidadAmbientes;
			}
			set
			{
				if ((this._CantidadAmbientes != value))
				{
					this.OnCantidadAmbientesChanging(value);
					this.SendPropertyChanging();
					this._CantidadAmbientes = value;
					this.SendPropertyChanged("CantidadAmbientes");
					this.OnCantidadAmbientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInquilino", DbType="Int")]
		public System.Nullable<int> IdInquilino
		{
			get
			{
				return this._IdInquilino;
			}
			set
			{
				if ((this._IdInquilino != value))
				{
					this.OnIdInquilinoChanging(value);
					this.SendPropertyChanging();
					this._IdInquilino = value;
					this.SendPropertyChanged("IdInquilino");
					this.OnIdInquilinoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
